### PR TITLE
Arzu

### PR DESCRIPTION
**Pull request by arzukizil**
Could you please review my code.
Best

### CODE REVIEW

**Comment by asiyeakpinar** [comment]
My dear Friends ,your code looks fantastic.I hope i can work with you in the same project.

**Review by asiyeakpinar — COMMENTED** [review]
this code looks better ,i am doing alright by the way.Sorry for the confision about not to assigned you as my assignee.
image

**Comment by arzukizil** [comment]
No worries Asiye. We're learning.
thank you

**Review by asiyeakpinar — APPROVED** [review]
well done ,fantastic

**Comment by AysegulSoytasCelik** [comment]
This is very important time.

**Review by asiyeakpinar — COMMENTED** [review]
this is a trial

**Review by asiyeakpinar — COMMENTED** [review]
hiiiii

**Comment by TugbaBorekci** [comment]
Good  Luck

**Pull request merged**
